In [8]:
import numpy as np

In [9]:
arr = np.random.randint(0,100, 10)

In [10]:
arr

array([ 7, 78,  4,  6, 49,  2, 53, 24, 97, 84])

In [11]:
arr.max()

97

In [12]:
arr.min()

2

In [13]:
arr.argmax()

8

In [14]:
arr.dtype

dtype('int32')

## Indexs

In [17]:
arr = np.arange(0,11)

In [18]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [19]:
arr[:5]

array([0, 1, 2, 3, 4])

In [20]:
new_arr = arr / 2

In [21]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [22]:
new_arr[5:]

array([2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
slide_arr = arr[0:4]

In [30]:
slide_arr[:] = 99

In [31]:
arr[:]

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr_copy = arr.copy()
arr_copy[:] = 88

print(arr_copy)
print(arr)

[88 88 88 88 88 88 88 88 88 88 88]
[99 99 99 99  4  5  6  7  8  9 10]


In [35]:
arr = np.arange(0,9)

In [37]:
arr_2d = arr.reshape(3,3)
print(arr_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
arr_2d.shape

(3, 3)

In [39]:
print(arr_2d[1])
print(arr_2d[1][1])
print(arr_2d[1,1])

[3 4 5]
4
4


In [41]:
print(arr_2d[:2])
print(arr_2d[:2,1:])

[[0 1 2]
 [3 4 5]]
[[1 2]
 [4 5]]


In [43]:
bool_arr = arr > 4

In [49]:
a = arr[bool_arr]

In [50]:
a

array([5, 6, 7, 8])

In [51]:
a[:] = 2

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
arr[arr <= 5]

array([0, 1, 2, 3, 4, 5])

## Operators

In [54]:
arr = np.arange(0,10)

In [55]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [56]:
(arr + 2) / 100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [57]:
1 / arr 

C:\Users\CuongND27\AppData\Local\Temp\ipykernel_9156\1952622374.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [58]:
arr / arr

C:\Users\CuongND27\AppData\Local\Temp\ipykernel_9156\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [60]:
np.log(arr)

C:\Users\CuongND27\AppData\Local\Temp\ipykernel_9156\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [61]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [63]:
print(arr.sum())
print(arr.min())
print(arr.max())

9

In [65]:
arr_2d = np.arange(1,13).reshape(3,4)

In [67]:
# sum across rows = cum cloumns
arr_2d.sum(axis=0)

array([15, 18, 21, 24])