In [1]:
import numpy as np

In [4]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
mymetrix = np.array(mylist)

In [6]:
mymetrix.shape

(3, 3)

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones((4,5)) + 100

array([[101., 101., 101., 101., 101.],
       [101., 101., 101., 101., 101.],
       [101., 101., 101., 101., 101.],
       [101., 101., 101., 101., 101.]])

In [14]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(3,5)

array([[0.77220958, 0.51331521, 0.20430809, 0.20742301, 0.31815573],
       [0.17007543, 0.4722855 , 0.5645185 , 0.69128495, 0.26876521],
       [0.9608495 , 0.53850721, 0.2860725 , 0.82368598, 0.5801406 ]])

In [18]:
np.random.randn(10)

array([ 1.75916039,  0.48482363, -1.82744559,  1.31576875,  0.49142687,
        0.448074  , -0.51416474,  2.18032667,  0.72883738, -2.30943377])

In [19]:
np.random.randint(1,1000,10)

array([581, 707, 827, 260, 349, 575, 804, 945, 758, 795])

In [23]:
np.random.seed(42)
np.random.rand(3,5)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

In [24]:
np.random.rand(3,5)

array([[0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
       [0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041]])

In [26]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])